import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // First, get the demo organization created in seed 02
  const organizations = await knex('organizations').where('slug', 'demo-org').select('id').first();
  const orgId = organizations?.id || 1;

  // Get the admin user for created_by
  const admin = await knex('users').where('organization_id', orgId).orderBy('id', 'asc').first();
  const adminUserId = admin?.id || 1;

  // Disable foreign key checks to avoid deletion constraint errors
  await knex.raw('SET FOREIGN_KEY_CHECKS = 0');

  // Clear existing data (in correct order to respect foreign keys)
  await knex('cost_centers').where('organization_id', orgId).del();
  await knex('designations').where('organization_id', orgId).del();
  await knex('departments').where('organization_id', orgId).del();
  // Delete locations BEFORE branches (locations has FK to branches)
  await knex('locations').where('organization_id', orgId).del();
  await knex('branches').where('organization_id', orgId).del();

  // Seed Branches
  const [branchId1, branchId2, branchId3] = await knex('branches').insert([
    {
      uuid: 'branch-001',
      organization_id: orgId,
      name: 'New Delhi',
      code: 'HQ',
      address_line1: '123 Business Street',
      address_line2: 'Floor 10',
      city: 'New Delhi',
      state: 'Delhi',
      country: 'India',
      postal_code: '110001',
      phone: '+91-11-1234-5678',
      email: 'delhi@apponext.com',
      website: 'www.apponext.com',
      is_primary: true,
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'branch-002',
      organization_id: orgId,
      name: 'Bangalore',
      code: 'BLR',
      address_line1: '456 Tech Park',
      address_line2: 'Building A',
      city: 'Bangalore',
      state: 'Karnataka',
      country: 'India',
      postal_code: '560001',
      phone: '+91-80-8765-4321',
      email: 'bangalore@apponext.com',
      is_primary: false,
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'branch-003',
      organization_id: orgId,
      name: 'Mumbai',
      code: 'MUM',
      address_line1: '789 Financial Hub',
      city: 'Mumbai',
      state: 'Maharashtra',
      country: 'India',
      postal_code: '400001',
      phone: '+91-22-2222-3333',
      email: 'mumbai@apponext.com',
      is_primary: false,
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]);

  // Seed Locations
  const [locId1, locId2, locId3, locId4] = await knex('locations').insert([
    {
      uuid: 'loc-001',
      organization_id: orgId,
      name: 'Arham IT Solution',
      code: 'ARHAM_AHILYANAGAR',
      type: 'office',
      branch_id: branchId1,
      address_line1: 'Ahilyanagar Tech Center',
      city: 'Ahilyanagar',
      state: 'Maharashtra',
      country: 'India',
      postal_code: '414001',
      latitude: 19.0948,
      longitude: 74.7480,
      geofence_radius_m: 500,
      timezone: 'Asia/Kolkata',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'loc-002',
      organization_id: orgId,
      name: 'Kosqu Technolab',
      code: 'KOSQU_NAVI_MUMBAI',
      type: 'office',
      branch_id: branchId2,
      address_line1: 'Navi Mumbai IT Park',
      city: 'Navi Mumbai',
      state: 'Maharashtra',
      country: 'India',
      postal_code: '400703',
      latitude: 19.0330,
      longitude: 73.0297,
      geofence_radius_m: 500,
      timezone: 'Asia/Kolkata',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'loc-003',
      organization_id: orgId,
      name: 'Work From Home',
      code: 'WFH',
      type: 'work',
      address_line1: 'Remote',
      timezone: 'Asia/Kolkata',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'loc-004',
      organization_id: orgId,
      name: 'Hybrid Location',
      code: 'HYBRID',
      type: 'office',
      branch_id: branchId2,
      city: 'Bangalore',
      timezone: 'Asia/Kolkata',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]);

  // Seed Departments
  const [deptId1, deptId2, deptId3, deptId4, deptId5] = await knex('departments').insert([
    {
      uuid: 'dept-001',
      organization_id: orgId,
      name: 'Engineering',
      code: 'ENG',
      description: 'Software Development',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'dept-002',
      organization_id: orgId,
      name: 'Human Resources',
      code: 'HR',
      description: 'HR and People Operations',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'dept-003',
      organization_id: orgId,
      name: 'Sales',
      code: 'SALES',
      description: 'Business Development',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'dept-004',
      organization_id: orgId,
      name: 'Finance',
      code: 'FINANCE',
      description: 'Financial Management',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'dept-005',
      organization_id: orgId,
      name: 'Operations',
      code: 'OPS',
      description: 'Business Operations',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]);

  // Seed Designations
  await knex('designations').insert([
    {
      uuid: 'desig-001',
      organization_id: orgId,
      name: 'Senior Manager',
      code: 'SM',
      department_id: deptId1,
      level: 4,
      description: 'Senior Management Role',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'desig-002',
      organization_id: orgId,
      name: 'Manager',
      code: 'MGR',
      department_id: deptId1,
      level: 3,
      description: 'Team Manager',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'desig-003',
      organization_id: orgId,
      name: 'Senior Developer',
      code: 'SD',
      department_id: deptId1,
      level: 2,
      description: 'Senior Development Role',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'desig-004',
      organization_id: orgId,
      name: 'Developer',
      code: 'DEV',
      department_id: deptId1,
      level: 1,
      description: 'Software Developer',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'desig-005',
      organization_id: orgId,
      name: 'HR Manager',
      code: 'HRM',
      department_id: deptId2,
      level: 3,
      description: 'HR Manager',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'desig-006',
      organization_id: orgId,
      name: 'Sales Manager',
      code: 'SALESMGR',
      department_id: deptId3,
      level: 3,
      description: 'Sales Manager',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'desig-007',
      organization_id: orgId,
      name: 'Finance Manager',
      code: 'FIN_MGR',
      department_id: deptId4,
      level: 3,
      description: 'Finance Manager',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'desig-008',
      organization_id: orgId,
      name: 'Operations Manager',
      code: 'OPS_MGR',
      department_id: deptId5,
      level: 3,
      description: 'Operations Manager',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]);

  // Seed Cost Centers
  await knex('cost_centers').insert([
    {
      uuid: 'cc-001',
      organization_id: orgId,
      name: 'Engineering Cost Center',
      code: 'ENG_CC',
      budget_amount: 5000000,
      currency: 'INR',
      description: 'Engineering Department Budget',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'cc-002',
      organization_id: orgId,
      name: 'Sales Cost Center',
      code: 'SALES_CC',
      budget_amount: 3000000,
      currency: 'INR',
      description: 'Sales Department Budget',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'cc-003',
      organization_id: orgId,
      name: 'Operations Cost Center',
      code: 'OPS_CC',
      budget_amount: 2000000,
      currency: 'INR',
      description: 'Operations Department Budget',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'cc-004',
      organization_id: orgId,
      name: 'HR Cost Center',
      code: 'HR_CC',
      budget_amount: 1000000,
      currency: 'INR',
      description: 'HR Department Budget',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
    {
      uuid: 'cc-005',
      organization_id: orgId,
      name: 'Finance Cost Center',
      code: 'FIN_CC',
      budget_amount: 1500000,
      currency: 'INR',
      description: 'Finance Department Budget',
      status: 'active',
      created_by: adminUserId,
      updated_by: adminUserId,
      created_at: new Date(),
      updated_at: new Date(),
    },
  ]);

  // Enable foreign key checks back
  await knex.raw('SET FOREIGN_KEY_CHECKS = 1');

  console.log('Master data seeding completed');
}
