import type { IdCardConfig } from '../types/idCardTemplate.types';

export const KOSQU_CORPORATE_CONFIG: IdCardConfig = {
  header: {
    visible: true,
    showLogo: true,
    logoUrl: null,
    logoInitial: 'K',
    logoSize: 42,
    orgName: 'KOSQU',
    orgNameColor: '#0f172a',
    subtitle: 'TECHNOLOGY • AI • GROWTH',
    subtitleColor: '#334155',
    headerBackground: 'transparent',
    statusBadge: {
      visible: false,
      type: 'auto',
      staticText: 'ACTIVE',
      colorVariant: 'emerald',
    },
  },
  photo: {
    visible: true,
    shape: 'square',
    size: 104,
    fallbackStyle: 'initials',
    fallbackBgColor: '#e2e8f0',
    fallbackTextColor: '#0f172a',
    borderWidth: 2,
    borderColor: '#0f172a',
    allowEmployeeUpload: true,
  },
  fields: [
    {
      id: 'field_name',
      key: 'name',
      label: 'Employee Name',
      visible: true,
      side: 'front',
      fontSize: 'lg',
      fontWeight: 'black',
      color: '#0f172a',
      showLabel: false,
    },
    {
      id: 'field_designation',
      key: 'designation',
      label: 'Designation',
      visible: true,
      side: 'front',
      fontSize: 'xs',
      fontWeight: 'bold',
      color: '#334155',
      showLabel: false,
    },
    {
      id: 'field_code',
      key: 'employeeCode',
      label: 'ID',
      visible: true,
      side: 'front',
      fontSize: 'sm',
      fontWeight: 'bold',
      color: '#0f172a',
      labelColor: '#0f172a',
      showLabel: true,
    },
  ],
  qrCode: {
    enabled: true,
    content: 'employee_code',
    position: 'bottom_right',
    side: 'front',
    size: 60,
    backgroundColor: '#ffffff',
    foregroundColor: '#0f172a',
  },
  footer: {
    visible: true,
    text: 'TECHNOLOGY • AI • GROWTH',
    textColor: '#0f172a',
    textSize: '9px',
    showPoweredBy: false,
    hrHelpline: 'info@kosqu.com',
  },
  back: {
    headerTitle: 'KOSQU',
    companyAddress: 'Kosqu Technolab',
    disclaimer:
      'This card is the property of Kosqu Technolab.\nIf found, please return.',
    showVerificationId: false,
    showQrCode: true,
    showSignatory: false,
    signatoryTitle: 'Authorized Signatory',
    signatureImageUrl: null,
    emergencyTitle: 'Emergency Contact:',
  },
  theme: {
    style: 'kosqu-corporate',
    cardLayout: 'kosqu-corporate',
    showLanyardHole: false,
    showRibbon: true,
    ribbonColor: '#f97316',
    barcodeFormat: 'barcode',
    tagline: 'TECHNOLOGY • AI • GROWTH',
    showDecorations: true,
    companyWebsite: 'www.kosqu.com',
    emergencyPhone: '+91 98765 43210',
    supportEmail: 'info@kosqu.com',
    primaryColor: '#0284c7',
    secondaryColor: '#ea580c',
    accentColor: '#f97316',
    gradientAngle: 135,
    gradientFrom: '#ffffff',
    gradientVia: '#f8fafc',
    gradientTo: '#f1f5f9',
    solidBgColor: '#ffffff',
    borderRadius: 20,
    fontFamily: 'Inter',
    textColor: '#0f172a',
    cardWidth: 320,
    cardHeight: 490,
    orientation: 'portrait',
  },
  print: {
    paperSize: 'A4',
    layout: '4-up',
    showCutGuides: true,
    bleedMm: 2,
    exportDpi: 300,
    exportMode: 'sheet',
  },
};

export const DEFAULT_ID_CARD_CONFIG: IdCardConfig = KOSQU_CORPORATE_CONFIG;
