import { ModuleNode } from './../types';

export const CEO_MODULES: ModuleNode[] = [
  {
    id: 'ceo_dashboard',
    name: 'Dashboard',
    description: 'Executive metrics, KPI statistics, headcount overview, and alerts',
    iconName: 'LayoutDashboard',
    defaultEnabled: true,
    children: [
      { id: 'ceo_dashboard_kpi_overview', name: 'KPI Overview', defaultEnabled: true },
      { id: 'ceo_dashboard_headcount_attrition', name: 'Headcount & Attrition', defaultEnabled: true },
      { id: 'ceo_dashboard_org_announcements', name: 'Announcements', defaultEnabled: true },
      { id: 'ceo_dashboard_notifications', name: 'System Notifications', defaultEnabled: true },
    ],
  },
  {
    id: 'ceo_core_hr',
    name: 'Core HR',
    description: 'Employee master directory, lifecycle, departments, and designations',
    iconName: 'Users',
    defaultEnabled: true,
    children: [
      { id: 'ceo_employee_directory', name: 'Employee Directory', defaultEnabled: true },
      { id: 'ceo_employee_lifecycle', name: 'Employee Lifecycle', defaultEnabled: true },
      { id: 'ceo_departments_governance', name: 'Departments', defaultEnabled: true },
      { id: 'ceo_designations_matrix', name: 'Designations', defaultEnabled: true },
      { id: 'ceo_org_structure', name: 'Org Structure', defaultEnabled: true },
    ],
  },
  {
    id: 'ceo_recruitment',
    name: 'Recruitment',
    description: 'MRF requests, job management, candidate pipeline, and offer approvals',
    iconName: 'Briefcase',
    defaultEnabled: true,
    children: [
      { id: 'ceo_recruitment_dashboard', name: 'Recruitment Dashboard', defaultEnabled: true },
      { id: 'ceo_interview_schedule', name: 'Interview Schedule', defaultEnabled: true },
      { id: 'ceo_mrf_approvals', name: 'MRF Request', defaultEnabled: true },
      { id: 'ceo_job_management', name: 'Job Management', defaultEnabled: true },
      { id: 'ceo_candidate_pipeline', name: 'Candidate Management', defaultEnabled: true },
      { id: 'ceo_candidate_report', name: 'Candidate Report', defaultEnabled: true },
      { id: 'ceo_resume_screening', name: 'Resume Screening', defaultEnabled: true },
      { id: 'ceo_applicant_tracker', name: 'Applicant Tracker', defaultEnabled: true },
      { id: 'ceo_assessment_mgmt', name: 'Assessment Management', defaultEnabled: true },
      { id: 'ceo_offer_approvals', name: 'Offer Management', defaultEnabled: true },
      { id: 'ceo_interviewer_ratings', name: 'Interviewer Ratings', defaultEnabled: true },
      { id: 'ceo_employee_referrals', name: 'Employee Referrals', defaultEnabled: true },
    ],
  },
  {
    id: 'ceo_attendance',
    name: 'Attendance',
    description: 'Daily attendance logs, live tracking, office locations, and breaks',
    iconName: 'Clock',
    defaultEnabled: true,
    children: [
      { id: 'ceo_attendance_dashboard', name: 'Attendance Dashboard', defaultEnabled: true },
      { id: 'ceo_live_tracking', name: 'Live Tracking', defaultEnabled: true },
      { id: 'ceo_location_management', name: 'Location Management', defaultEnabled: true },
      { id: 'ceo_location_mapping', name: 'Location Access Mapping', defaultEnabled: true },
      { id: 'ceo_break_logs', name: 'Break Logs', defaultEnabled: true },
    ],
  },
  {
    id: 'ceo_shift_management',
    name: 'Shift Management',
    description: 'General work shifts and rotational rosters',
    iconName: 'CalendarCheck',
    defaultEnabled: true,
    children: [
      { id: 'ceo_general_shifts', name: 'General Shift', defaultEnabled: true },
      { id: 'ceo_roster_shifts', name: 'Roster Shift', defaultEnabled: true },
    ],
  },
  {
    id: 'ceo_leave_management',
    name: 'Leave Management',
    description: 'Leave approvals, approvals hub, leave settings, and holidays',
    iconName: 'Palmtree',
    defaultEnabled: true,
    children: [
      { id: 'ceo_leave_approvals_inbox', name: 'Leave Approvals', defaultEnabled: true },
      { id: 'ceo_approvals_dashboard', name: 'Approvals Dashboard', defaultEnabled: true },
      { id: 'ceo_leave_policies', name: 'Leave Settings', defaultEnabled: true },
      { id: 'ceo_holiday_calendar', name: 'Holiday Management', defaultEnabled: true },
    ],
  },
  {
    id: 'ceo_payroll',
    name: 'Payroll',
    description: 'Salary structures, payroll processing, revisions, and reports',
    iconName: 'Wallet',
    defaultEnabled: true,
    children: [
      { id: 'ceo_payroll_dashboard', name: 'Payroll Dashboard', defaultEnabled: true },
      { id: 'ceo_payroll_master_settings', name: 'Payroll Master Settings', defaultEnabled: true },
      { id: 'ceo_salary_revisions', name: 'Salary Revision', defaultEnabled: true },
      { id: 'ceo_payroll_processing', name: 'Payroll Processing', defaultEnabled: true },
      { id: 'ceo_payslip_management', name: 'Payslip Management', defaultEnabled: true },
      { id: 'ceo_mass_salary_upload', name: 'Mass Salary Upload', defaultEnabled: true },
      { id: 'ceo_payroll_reports', name: 'Payroll Reports', defaultEnabled: true },
      { id: 'ceo_fnf_settlements', name: 'Settlements', defaultEnabled: true },
    ],
  },
  {
    id: 'ceo_loan_management',
    name: 'Loan Management',
    description: 'Loan types, requests, and disbursal approvals',
    iconName: 'ReceiptIndianRupee',
    defaultEnabled: true,
    children: [
      { id: 'ceo_loan_types', name: 'Loan Type Settings', defaultEnabled: true },
      { id: 'ceo_loan_requests', name: 'Loan Requests & Disbursal', defaultEnabled: true },
    ],
  },
  {
    id: 'ceo_expense_management',
    name: 'Expense Management',
    description: 'Employee expense claims, reimbursements, and approvals',
    iconName: 'ReceiptIndianRupee',
    defaultEnabled: true,
    children: [
      { id: 'ceo_expense_claims', name: 'Expense Claims', defaultEnabled: true },
    ],
  },
  {
    id: 'ceo_travel_management',
    name: 'Travel Management',
    description: 'Corporate travel requests, bookings, and approvals',
    iconName: 'Plane',
    defaultEnabled: true,
    children: [
      { id: 'ceo_travel_requests', name: 'Travel Request', defaultEnabled: true },
    ],
  },
  {
    id: 'ceo_pms',
    name: 'PMS',
    description: 'Goals & OKRs, review cycles, and performance appraisals',
    iconName: 'Target',
    defaultEnabled: true,
    children: [
      { id: 'ceo_pms_dashboard', name: 'PMS Dashboard', defaultEnabled: true },
      { id: 'ceo_goals_okrs', name: 'Goals & OKRs', defaultEnabled: true },
      { id: 'ceo_performance_reviews', name: 'Review Cycles', defaultEnabled: true },
      { id: 'ceo_appraisals_rewards', name: 'Appraisals', defaultEnabled: true },
    ],
  },
  {
    id: 'ceo_asset_management',
    name: 'Asset Management',
    description: 'Hardware fleet, software licenses, and equipment tracking',
    iconName: 'Package',
    defaultEnabled: true,
    children: [
      { id: 'ceo_asset_dashboard', name: 'Asset Dashboard', defaultEnabled: true },
      { id: 'ceo_asset_inventory', name: 'Asset Inventory', defaultEnabled: true },
      { id: 'ceo_software_licenses', name: 'Software Licenses', defaultEnabled: true },
    ],
  },
  {
    id: 'ceo_reports_analytics',
    name: 'Reports & Analytics',
    description: 'Consolidated attendance summaries, timelogs, and analytics',
    iconName: 'BarChart3',
    defaultEnabled: true,
    children: [
      { id: 'ceo_attendance_reports', name: 'Attendance Reports', defaultEnabled: true },
      { id: 'ceo_timelog_analytics', name: 'Timelog Reports', defaultEnabled: true },
    ],
  },
  {
    id: 'ceo_hr_operations',
    name: 'HR Operations',
    description: 'Workflow automations, employee requests, and company announcements',
    iconName: 'GitMerge',
    defaultEnabled: true,
    children: [
      { id: 'ceo_employee_requests', name: 'Employee Requests', defaultEnabled: true },
      { id: 'ceo_workflow_builder', name: 'Workflows', defaultEnabled: true },
      { id: 'ceo_announcements_hub', name: 'Announcements', defaultEnabled: true },
    ],
  },
  {
    id: 'ceo_masters',
    name: 'Masters',
    description: 'Company profiles, branches, grade bands, and templates',
    iconName: 'FolderKanban',
    defaultEnabled: true,
    children: [
      { id: 'ceo_company_locations_master', name: 'Company & Locations', defaultEnabled: true },
      { id: 'ceo_grade_band_master', name: 'Grade Bands', defaultEnabled: true },
      { id: 'ceo_notification_templates', name: 'Notification Templates', defaultEnabled: true },
      { id: 'ceo_kra_templates', name: 'KRA Templates', defaultEnabled: true },
    ],
  },
];
