import type { IdCardConfig } from '../types/idCard.types';

export const KOSQU_CORPORATE_CONFIG: IdCardConfig = {
  header: {
    visible: true,
    showLogo: true,
    logoUrl: null,
    logoInitial: 'K',
    logoSize: 42,
    orgName: 'KOSQU',
    orgNameColor: '#0f172a',
    subtitle: 'TECHNOLOGY • AI • GROWTH',
    subtitleColor: '#334155',
    headerBackground: 'transparent',
    statusBadge: {
      visible: false,
      type: 'auto',
      staticText: 'ACTIVE',
      colorVariant: 'emerald',
    },
  },
  photo: {
    visible: true,
    shape: 'square',
    size: 104,
    fallbackStyle: 'initials',
    fallbackBgColor: '#e2e8f0',
    fallbackTextColor: '#0f172a',
    borderWidth: 2,
    borderColor: '#0f172a',
    allowEmployeeUpload: true,
  },
  fields: [
    {
      id: 'field_name',
      key: 'name',
      label: 'Employee Name',
      visible: true,
      side: 'front',
      fontSize: 'lg',
      fontWeight: 'black',
      color: '#0f172a',
      showLabel: false,
    },
    {
      id: 'field_designation',
      key: 'designation',
      label: 'Designation',
      visible: true,
      side: 'front',
      fontSize: 'xs',
      fontWeight: 'bold',
      color: '#334155',
      showLabel: false,
    },
    {
      id: 'field_code',
      key: 'employeeCode',
      label: 'ID',
      visible: true,
      side: 'front',
      fontSize: 'sm',
      fontWeight: 'bold',
      color: '#0f172a',
      labelColor: '#0f172a',
      showLabel: true,
    },
  ],
  qrCode: {
    enabled: true,
    content: 'employee_code',
    position: 'bottom_right',
    side: 'front',
    size: 60,
    backgroundColor: '#ffffff',
    foregroundColor: '#0f172a',
    payloadType: 'vcard',
    errorCorrection: 'M',
    customUrlTemplate: '',
    fgColor: '#0b1e36',
    bgColor: '#ffffff',
  },
  qrConfig: {
    enabled: true,
    content: 'employee_code',
    position: 'bottom_right',
    side: 'front',
    size: 60,
    backgroundColor: '#ffffff',
    foregroundColor: '#0f172a',
    payloadType: 'vcard',
    errorCorrection: 'M',
    customUrlTemplate: '',
    fgColor: '#0b1e36',
    bgColor: '#ffffff',
  },
  footer: {
    visible: true,
    text: 'TECHNOLOGY • AI • GROWTH',
    textColor: '#0f172a',
    textSize: '9px',
    showPoweredBy: false,
    hrHelpline: 'info@kosqu.com',
  },
  back: {
    headerTitle: 'KOSQU',
    companyAddress: 'Kosqu Technolab',
    disclaimer:
      'This card is the property of Kosqu Technolab.\nIf found, please return.',
    showVerificationId: false,
    showQrCode: true,
    showSignatory: false,
    signatoryTitle: 'Authorized Signatory',
    signatureImageUrl: null,
    emergencyTitle: 'Emergency Contact:',
  },
  theme: {
    style: 'kosqu-corporate',
    cardLayout: 'kosqu-corporate',
    showLanyardHole: false,
    showRibbon: true,
    ribbonColor: '#f97316',
    barcodeFormat: 'barcode',
    tagline: 'TECHNOLOGY • AI • GROWTH',
    showDecorations: true,
    companyWebsite: 'www.kosqu.com',
    emergencyPhone: '+91 98765 43210',
    supportEmail: 'info@kosqu.com',
    primaryColor: '#0284c7',
    secondaryColor: '#ea580c',
    accentColor: '#f97316',
    gradientAngle: 135,
    gradientFrom: '#ffffff',
    gradientVia: '#f8fafc',
    gradientTo: '#f1f5f9',
    solidBgColor: '#ffffff',
    borderRadius: 20,
    fontFamily: 'Inter',
    textColor: '#0f172a',
    cardWidth: 320,
    cardHeight: 490,
    orientation: 'portrait',
  },
  print: {
    paperSize: 'A4',
    layout: '4-up',
    showCutGuides: true,
    bleedMm: 2,
    exportDpi: 300,
    exportMode: 'sheet',
  },
};

export const DEFAULT_ID_CARD_CONFIG: IdCardConfig = KOSQU_CORPORATE_CONFIG;

export const AVAILABLE_FIELDS_LIBRARY = [
  { key: 'name', label: 'Employee Name', defaultSide: 'front', defaultShowLabel: false },
  { key: 'designation', label: 'Designation / Job Title', defaultSide: 'front', defaultShowLabel: false },
  { key: 'department', label: 'Department Name', defaultSide: 'front', defaultShowLabel: false },
  { key: 'employeeCode', label: 'Employee Code / ID', defaultSide: 'front', defaultShowLabel: true },
  { key: 'employeeType', label: 'Employment Type (Full-Time/Contract)', defaultSide: 'front', defaultShowLabel: true },
  { key: 'dateOfJoining', label: 'Joined / Hire Date', defaultSide: 'front', defaultShowLabel: true },
  { key: 'bloodGroup', label: 'Blood Group', defaultSide: 'back', defaultShowLabel: true },
  { key: 'emergencyContact', label: 'Emergency Contact Phone', defaultSide: 'back', defaultShowLabel: true },
  { key: 'location', label: 'Branch / Work Location', defaultSide: 'back', defaultShowLabel: true },
  { key: 'phone', label: 'Work Mobile Number', defaultSide: 'back', defaultShowLabel: true },
  { key: 'email', label: 'Work Email Address', defaultSide: 'back', defaultShowLabel: true },
  { key: 'reportingManager', label: 'Reporting Manager', defaultSide: 'back', defaultShowLabel: true },
  { key: 'grade', label: 'Grade / Level', defaultSide: 'back', defaultShowLabel: true },
  { key: 'hrHelpline', label: 'Corporate HR Helpline', defaultSide: 'back', defaultShowLabel: true },
];

export const THEME_COLOR_PRESETS = [
  {
    name: 'Kosqu Official (White & Blue)',
    from: '#ffffff',
    via: '#ffffff',
    to: '#ffffff',
    primary: '#0284c7',
    solidBg: '#ffffff',
    badge: 'cyan',
    textColor: '#0f172a',
    isKosqu: true,
  },
  {
    name: 'Corporate Ocean Blue',
    from: '#0284c7',
    via: '#0284c7',
    to: '#0284c7',
    primary: '#0284c7',
    solidBg: '#ffffff',
    badge: 'cyan',
    textColor: '#0f172a',
  },
  {
    name: 'Emerald Green',
    from: '#059669',
    via: '#059669',
    to: '#059669',
    primary: '#059669',
    solidBg: '#ffffff',
    badge: 'emerald',
    textColor: '#0f172a',
  },
  {
    name: 'Royal Purple',
    from: '#7c3aed',
    via: '#7c3aed',
    to: '#7c3aed',
    primary: '#7c3aed',
    solidBg: '#ffffff',
    badge: 'purple',
    textColor: '#0f172a',
  },
  {
    name: 'Crimson Red',
    from: '#e11d48',
    via: '#e11d48',
    to: '#e11d48',
    primary: '#e11d48',
    solidBg: '#ffffff',
    badge: 'rose',
    textColor: '#0f172a',
  },
  {
    name: 'Midnight Dark',
    from: '#0f172a',
    via: '#0f172a',
    to: '#0f172a',
    primary: '#38bdf8',
    solidBg: '#0f172a',
    badge: 'blue',
    textColor: '#ffffff',
  },
];

export const FONT_OPTIONS = [
  { label: 'Inter (Modern Clean)', value: 'Inter, system-ui, sans-serif' },
  { label: 'Outfit (Geometric Bold)', value: 'Outfit, sans-serif' },
  { label: 'Roboto (Standard Sans)', value: 'Roboto, sans-serif' },
  { label: 'Poppins (Contemporary)', value: 'Poppins, sans-serif' },
  { label: 'Montserrat (Corporate)', value: 'Montserrat, sans-serif' },
  { label: 'Space Grotesk (Tech Modern)', value: '"Space Grotesk", monospace' },
];
