export const leavePermissions = [
  {
    code: 'leave.read',
    module: 'leave',
    resource: 'application',
    action: 'read',
    description: 'View leave applications',
    isSystem: true,
  },
  {
    code: 'leave.apply',
    module: 'leave',
    resource: 'application',
    action: 'apply',
    description: 'Apply for leave',
    isSystem: true,
  },
  {
    code: 'leave.approve',
    module: 'leave',
    resource: 'application',
    action: 'approve',
    description: 'Approve leave applications',
    isSystem: true,
  },
  {
    code: 'leave.admin',
    module: 'leave',
    resource: 'management',
    action: 'admin',
    description: 'Administer leave management',
    isSystem: true,
  },
  {
    code: 'leave.policy.manage',
    module: 'leave',
    resource: 'policy',
    action: 'manage',
    description: 'Manage leave policies',
    isSystem: true,
  },
  {
    code: 'leave.balance.manage',
    module: 'leave',
    resource: 'balance',
    action: 'manage',
    description: 'Manage leave balances',
    isSystem: true,
  },
  {
    code: 'leave.comp_off',
    module: 'leave',
    resource: 'comp_off',
    action: 'manage',
    description: 'Manage comp off',
    isSystem: true,
  },
  {
    code: 'leave.analytics',
    module: 'leave',
    resource: 'analytics',
    action: 'view',
    description: 'View leave analytics',
    isSystem: true,
  },
];
