import { Building2 } from 'lucide-react';
import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import type { AdminDashboardData } from '../hooks/useAdminDashboard';

type Department = AdminDashboardData['departmentBreakdown'][number];
export function DepartmentDistributionCard({ departments, className = '' }: { departments: Department[]; className?: string }) {
  const [hoveredDepartmentId, setHoveredDepartmentId] = useState<number | null>(null);
  const hoveredDepartment = departments.find((item) => item.id === hoveredDepartmentId);
  return <Card onMouseLeave={() => setHoveredDepartmentId(null)} className={`department-distribution-card dashboard-panel relative ${className}`}><CardHeader className="p-4 pb-2 sm:p-5 sm:pb-2"><CardTitle className="flex items-center gap-2 text-sm font-bold"><Building2 className="size-4 text-primary" /> Department distribution</CardTitle><CardDescription className="text-xs">Active employees by team</CardDescription></CardHeader><CardContent className="p-4 pt-1 sm:p-5 sm:pt-1">
    {!departments.length ? <div className="dashboard-empty h-52"><Building2 className="text-primary" /><span className="font-semibold text-foreground">No Department Data</span></div> : <div className="space-y-2 pt-2">{departments.slice(0, 8).map((department) => { const max = Math.max(...departments.map((item) => item.count), 1); return <div key={department.id} onMouseEnter={() => setHoveredDepartmentId(department.id)} className="grid grid-cols-[minmax(72px,110px)_minmax(0,1fr)_auto] items-center gap-2 rounded-lg px-1.5 py-1 text-[11px] transition-colors hover:bg-primary/8 dark:hover:bg-primary/10"><span className="truncate text-left font-medium text-muted-foreground">{department.name}</span><div className="h-3.5 overflow-hidden rounded-full bg-primary/8 dark:bg-primary/10"><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${Math.max((department.count / max) * 100, 5)}%` }} /></div><strong className="min-w-6 tabular-nums text-foreground">{department.count}</strong></div>; })}</div>}
  </CardContent>{hoveredDepartment && <div className="absolute left-0 top-full z-30 mt-2 w-full rounded-xl border border-border bg-popover p-3 text-popover-foreground shadow-soft-lg"><div className="mb-2 flex items-center justify-between gap-2"><p className="truncate text-xs font-bold">{hoveredDepartment.name} employees</p><span className="text-[10px] text-muted-foreground">{hoveredDepartment.count} total</span></div><div className="flex flex-wrap gap-1.5">{hoveredDepartment.employees.length ? hoveredDepartment.employees.map((employee) => <span key={employee.id} className="rounded-md bg-primary/8 px-1.5 py-1 text-[10px] font-medium text-primary dark:bg-primary/15">{employee.name}</span>) : <span className="text-[10px] text-muted-foreground">No active employees assigned.</span>}</div></div>}</Card>;
}
